### ISSUE TITLE
can't create claim

### ISSUE THREAD

**Issue by bibash28** [0xPolygonID/polygonid-flutter-sdk#246]
https://issuer-demo.polygonid.me/main

Create claim throws `can't create claim`.

**Comment by hawkbee1** [comment]
Same issue on issuer demo website when using official polygon ID app. Authentication is working but I can't create claims anymore.

**Comment by Plumillon** [comment]
The problem has been noticed, we are on it :)

**Comment by bibash28** [comment]
thanks
