### ISSUE TITLE
How to verify membership?

### ISSUE THREAD

**Issue by bibash28** [0xPolygonID/polygonid-flutter-sdk#252]
Sign in flow:
![image](https://user-images.githubusercontent.com/18188709/229474507-39365169-7ea2-4c3b-bc93-c3c7cd9258d3.png)

**Comment by hawkbee1** [comment]
Just reproduce issue with polygon ID app. here is technical information displayed by verifier website:

auth request: 
id: "21dedabf-098f-497c-bff6-81a6c58b5dab"
typ: "application/iden3comm-plain-json"
type: "https://iden3-communication.io/authorization/1.0/request"
thid: "21dedabf-098f-497c-bff6-81a6c58b5dab"
body:
callbackUrl: "https://self-hosted-demo-backend-platform.polygonid.me/api/callback?sessionId=138118"
reason: "test flow"
scope:
from: "did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5"

Zero knowledge proof information: 
authResponse:
id: "14e2af0d-a94c-4987-ba3c-111e40be7bde"
typ: "application/iden3comm-plain-json"
type: "https://iden3-communication.io/authorization/1.0/response"
thid: "21dedabf-098f-497c-bff6-81a6c58b5dab"
body:
did_doc:
@context: Array[1] ["https://www.w3.org/ns/did/v1"]
id: "did:polygonid:polygon:mumbai:2qEdd6YGs5VhA3BDuirP2WmcfTkUSUdizfjK4VjNLU"
service: Array[1] [{"id":"did:polygonid:polygon:mumbai:2qEdd6YGs5VhA3BDuirP2WmcfTkUSUdizfjK4VjNLU#push","type":"push-notification","serviceEndpoint":"https://push-staging.polygonid.com/api/v1","metadata":{"devices":[{"ciphertext":"PZKxQyUoqr2PVqsEtVYffYtb1lFCcr4f89NFvgxqVLmq0mqJW7/CZiaZU8pg3Rfbj6Q9xXR7G//zNpFBGbn2D5+BWMyeqa/2lpKJEkzIYOj0+U9Bdo1R5tsu8A4zMs3IhEFcX/QUKY5EzunbDQdN+yRAdO+tZq4ri5QoKYDt6ApTUxdbRlBNoKkLhbpyOzKXK7ueqIggZwM3hQ/970bXYmIbhvpcGhzp+LAO8N/5RSNgR0Eoje1SkD5RKkd2Ur0ck9vRuKyFxttHo8JNcKm9wHtAlLGIrd7AfeIEbYgFOIihNP1F+eBcfWElTa0G6AHeI2hMX25a0s/OO9ERsoqA1qOmWQZpnKGyHtdGWh5OR5YCItFviCaV2bTYAcc5156gVE/vZrc3t+RcXHlIEwDFSorq7B6tgKmGXouCahAk2ZIG9RhXSuPwiMU1E7reKmfF5WWHTKWauUBlVpn91R8TS81QfD5cStwkKgUf8hZHyxYW3rdDXDY2YEB85EDJEPa0zDzScX6iP8TLhB6ICWKBFhuBtTFeMCS6m9ndJgm7wJ321be1Z07kjynzIyYnSO7Eup4S3WcgYgEQN3CFsNPdTJu/gskfhXCDS6jI8Bv70x2joP/DpAprqfu4KzQZ2Y7nxFmut2GHmE+BeLkLZNw1IA//TJpj/+8b5ogPlD/e5jU=","alg":"RSA-OAEP-512"}]}}]
scope:
from: "did:polygonid:polygon:mumbai:2qEdd6YGs5VhA3BDuirP2WmcfTkUSUdizfjK4VjNLU"
to: "did:polygonid:polygon:mumbai:2qH7XAwYQzCp9VfhpNgeLtK2iCehDDrfMWUCEg5ig5"
id: "did:polygonid:polygon:mumbai:2qEdd6YGs5VhA3BDuirP2WmcfTkUSUdizfjK4VjNLU"
jwz: "eyJhbGciOiJncm90aDE2IiwiY2lyY3VpdElkIjoiYXV0aFYyIiwiY3JpdCI6WyJjaXJjdWl0SWQiXSwidHlwIjoiYXBwbGljYXRpb24vaWRlbjMtemtwLWpzb24ifQ.eyJpZCI6IjE0ZTJhZjBkLWE5NGMtNDk4Ny1iYTNjLTExMWU0MGJlN2JkZSIsInR5cCI6ImFwcGxpY2F0aW9uL2lkZW4zY29tbS1wbGFpbi1qc29uIiwidHlwZSI6Imh0dHBzOi8vaWRlbjMtY29tbXVuaWNhdGlvbi5pby9hdXRob3JpemF0aW9uLzEuMC9yZXNwb25zZSIsInRoaWQiOiIyMWRlZGFiZi0wOThmLTQ5N2MtYmZmNi04MWE2YzU4YjVkYWIiLCJmcm9tIjoiZGlkOnBvbHlnb25pZDpwb2x5Z29uOm11bWJhaToycUVkZDZZR3M1VmhBM0JEdWlyUDJXbWNmVGtVU1VkaXpmaks0VmpOTFUiLCJ0byI6ImRpZDpwb2x5Z29uaWQ6cG9seWdvbjptdW1iYWk6MnFIN1hBd1lRekNwOVZmaHBOZ2VMdEsyaUNlaEREcmZNV1VDRWc1aWc1IiwiYm9keSI6eyJkaWRfZG9jIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy9ucy9kaWQvdjEiXSwiaWQiOiJkaWQ6cG9seWdvbmlkOnBvbHlnb246bXVtYmFpOjJxRWRkNllHczVWaEEzQkR1aXJQMldtY2ZUa1VTVWRpemZqSzRWak5MVSIsInNlcnZpY2UiOlt7ImlkIjoiZGlkOnBvbHlnb25pZDpwb2x5Z29uOm11bWJhaToycUVkZDZZR3M1VmhBM0JEdWlyUDJXbWNmVGtVU1VkaXpmaks0VmpOTFUjcHVzaCIsInR5cGUiOiJwdXNoLW5vdGlmaWNhdGlvbiIsInNlcnZpY2VFbmRwb2ludCI6Imh0dHBzOi8vcHVzaC1zdGFnaW5nLnBvbHlnb25pZC5jb20vYXBpL3YxIiwibWV0YWRhdGEiOnsiZGV2aWNlcyI6W3siY2lwaGVydGV4dCI6IlBaS3hReVVvcXIyUFZxc0V0VllmZll0YjFsRkNjcjRmODlORnZneHFWTG1xMG1xSlc3L0NaaWFaVThwZzNSZmJqNlE5eFhSN0cvL3pOcEZCR2JuMkQ1K0JXTXllcWEvMmxwS0pFa3pJWU9qMCtVOUJkbzFSNXRzdThBNHpNczNJaEVGY1gvUVVLWTVFenVuYkRRZE4reVJBZE8rdFpxNHJpNVFvS1lEdDZBcFRVeGRiUmxCTm9La0xoYnB5T3pLWEs3dWVxSWdnWndNM2hRLzk3MGJYWW1JYmh2cGNHaHpwK0xBTzhOLzVSU05nUjBFb2plMVNrRDVSS2tkMlVyMGNrOXZSdUt5Rnh0dEhvOEpOY0ttOXdIdEFsTEdJcmQ3QWZlSUViWWdGT0lpaE5QMUYrZUJjZldFbFRhMEc2QUhlSTJoTVgyNWEwcy9PTzlFUnNvcUExcU9tV1FacG5LR3lIdGRHV2g1T1I1WUNJdEZ2aUNhVjJiVFlBY2M1MTU2Z1ZFL3ZacmMzdCtSY1hIbElFd0RGU29ycTdCNnRnS21HWG91Q2FoQWsyWklHOVJoWFN1UHdpTVUxRTdyZUttZkY1V1dIVEtXYXVVQmxWcG45MVI4VFM4MVFmRDVjU3R3a0tnVWY4aFpIeXhZVzNyZERYRFkyWUVCODVFREpFUGEwekR6U2NYNmlQOFRMaEI2SUNXS0JGaHVCdFRGZU1DUzZtOW5kSmdtN3dKMzIxYmUxWjA3a2p5bnpJeVluU083RXVwNFMzV2NnWWdFUU4zQ0ZzTlBkVEp1L2dza2ZoWENEUzZqSThCdjcweDJqb1AvRHBBcHJxZnU0S3pRWjJZN254Rm11dDJHSG1FK0JlTGtMWk53MUlBLy9USnBqLys4YjVvZ1BsRC9lNWpVPSIsImFsZyI6IlJTQS1PQUVQLTUxMiJ9XX19XX0sIm1lc3NhZ2UiOm51bGwsInNjb3BlIjpbXX19.eyJwcm9vZiI6eyJwaV9hIjpbIjMyOTAxNzc2NDc3ODA2NDM1NTQ3ODMxMTYzOTcyMzc0OTg0OTAyMDgwNzQyMjk3MjYwMjE3ODAxMTY4MjM5MTk4ODk0MzUzMzExODQiLCIxNDQ0Mjc2OTE2MzY2MDE4NzQ1NTkyMDQwNjY0MzkwNDQyNTgxNjEzNTI1NTc4OTA1MzU4NjQ2NzAwNTU3NjI5ODA0NDg1MjU5NDI4NCIsIjEiXSwicGlfYiI6W1siMTE0MTAzMDI3MTczNDQxMDIxMjcyMzU2NjEwNjU2MDI3NjU5OTEwNDgwNzcwMjcwMDQ1MDYyMTQ4MzIyNjg3OTM1NDczNTY1ODk3MzciLCIyOTk1MDcyNzY3ODc3NjI0NDA2NzczMDU5NzUyODc3Mzg0OTMxOTc4MTExMDc0MzU1OTQ2Mjk0Nzg4Nzk2OTM4ODA2NDg5NjIyNjg5Il0sWyIxMDkxODczNzk2NTMzNjY3MTAyMDA5MzM3NzI0NjQ0NzE0NjY5NDIzMTc2ODc1Mjc2NjYwOTIyODczMzk2NjM3Nzk0MzQ2MDM4MzMyOCIsIjIwMjIzNzQ2NzQyNzkxMzc5MDE2NjgyMTg3OTg5MjU0NTc1MTIwMjgwNTk2MDMyNTY4MDUwNDU2MDM5NjI5MzM4Nzg3MjI5MjQyOTEyIl0sWyIxIiwiMCJdXSwicGlfYyI6WyI4MTc1OTgwOTg1OTMwNTAxMzg4MTkzMjExNDU0MjY3ODIxNTkxMDg2NTM0NDA2MTI0MjM3MTcwNjQzNTQ1ODg3MzgyMTU1NzQ4ODI0IiwiMTU3MTM1NDcyNzE0ODU4MTk4MjM0MDkzMTE4NDcwMjM4OTQ3MTE5NDUyOTUxMzY4MDczNDczNjMzNzA5MzI1ODc0ODEyMTk1NjA3NDAiLCIxIl0sInByb3RvY29sIjoiZ3JvdGgxNiIsImN1cnZlIjoiYm4xMjgifSwicHViX3NpZ25hbHMiOlsiMjQ1MDgyMTY5MjAyMjU1MDk0MDAzNjk3NTM1Nzk4NjQyODAxNTYyMzQzMDI5MzUyNjg1NTczMDQ3OTgxMDUzNjE5NjU4NDcwNDIiLCIxMzY3NjI0MjYwNTQ2MzM1NDg5NTY0NDQ5NjM3NTgxODMxNzIwMzQxNDk4NDY3NzYxMDM2MDQ5MDg1NDI1MDEwMjk3MTQ4OTY5MjYwNiIsIjY0NjAxMjU1ODgwMTA3OTMzOTI4ODAzNTMyMTY3MDY4NjQzODY1OTQ3NTgzOTgyMTgyNDQyMDc2ODU3OTAzNzUwMDQ1ODUyNzcwNzYiXX0"
proofs:

**Comment by bibash28** [comment]
UX issue in https://verifier-demo.polygonid.me... it is solved now..
