### ISSUE TITLE
How to map credential subject data into proper string?

### ISSUE THREAD

**Issue by bibash28** [0xPolygonID/polygonid-flutter-sdk#289]
Opened in : https://github.com/iden3/claim-schema-vocab/issues/25

**Comment by rauljareno** [comment]
@bibash28 I think what you need is this, right?

`String conditionTitle = "";
      String conditionMsg = "";
      String credentialValue = claimModel?.credentialValues
              .firstWhere((element) => element.name == reqKey)
              .value ??
          reqKey;
      if (conditionKey == "\$eq") {
        type = ProofRequestType.private_proof_with_equal_operator;
        conditionTitle = reqKey;
        conditionMsg = "is";
      } else if (conditionKey == "\$lt") {
        conditionTitle = reqKey;
        conditionMsg = "is smaller than";
      } else if (conditionKey == "\$gt") {
        conditionTitle = reqKey;
        conditionMsg = "is bigger than";
      } else if (conditionKey == "\$in") {
        conditionTitle = reqKey;
        conditionMsg = "is one of the following values:\n";
      } else if (conditionKey == "\$nin") {
        conditionTitle = reqKey;
        conditionMsg = "is not one of the following values:\n";
      } else if (conditionKey == "\$ne") {
        conditionTitle = reqKey;
        conditionMsg = "is not";
      }
      if (conditionValue is List) {
        conditionMsg = "$conditionMsg\n";
        for (var val in conditionValue) {
          conditionMsg = "$conditionMsg - $val";
          conditionMsg = "$conditionMsg\n";
        }
        conditionMsg = conditionMsg.substring(0, conditionMsg.length - 1);
      } else {
        conditionMsg = "$conditionMsg $conditionValue";
      }`

**Comment by bibash28** [comment]
Need more code. Yes, this is what I want.  @rauljareno

**Comment by bibash28** [comment]
If this stuff will be added in example app, then it will be great help to developers...

**Comment by rauljareno** [comment]
We are having it in mind and will improve further with the feedback the example app, but as of now, this is an UI translation of the iden3message and it depends on the integrator's choice of how to show the information.
