### ISSUE TITLE
How to generater proof?

### ISSUE THREAD

**Issue by bibash28** [0xPolygonID/polygonid-flutter-sdk#296]
What is the function called here?

I was doing
```
      await sdk.iden3comm.authenticate(
        message: iden3MessageEntity,
        genesisDid: did,
        privateKey: privateKey,
      );
```

<img width="696" alt="image" src="https://user-images.githubusercontent.com/18188709/236732650-8dff3385-200d-4880-9360-355b6eb5bb0d.png">

**Comment by bibash28** [comment]
When calling authenticate

```
flutter: Status: 0
flutter: status is not OK: 0. Error: Get "https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld": context deadline exceeded
```

**Comment by bibash28** [comment]
App is also crashing

```
* thread #47, name = 'DartWorker', stop reason = EXC_BAD_ACCESS (code=1, address=0x58)
    frame #0: 0x0000000104fe7e0c Runner`github.com/0xPolygonID/c-polygonid.queryFromObjMerklized + 716
Runner`github.com/0xPolygonID/c-polygonid.queryFromObjMerklized:
->  0x104fe7e0c <+716>: ldr    x1, [x1, #0x58]
    0x104fe7e10 <+720>: mov    x0, x2
    0x104fe7e14 <+724>: blr    x1
    0x104fe7e18 <+728>: ldr    x3, [sp, #0x260]
Target 0: (Runner) stopped.
Lost connection to device.
```

**Comment by syubbanfy** [comment]
same here, i can't find the prove usage & loadCircuitFiles. Then i got NullAtomicQueryInputsException when scanning verifier, maybe i could get more detailed error rather than returning the instance of error?

**Comment by rauljareno** [comment]
for checking how to download the circuit files, please check the example app example/lib/src/presentation/ui/splash/splash_bloc.dart

`prove` method in proof.dart is used internally when iden3comm.dart `getProofs` method passing an iden3 message. This method is used in case of wanting to generate a proof without a request from an external verifier.

**Comment by syubbanfy** [comment]
could you give an example? there are two parameters without example
1. required ClaimEntity claim,
2. required CircuitDataEntity circuitData
