### ISSUE TITLE
Authentication Fails in example app

### ISSUE THREAD

**Issue by tranngocthuan1996** [0xPolygonID/polygonid-flutter-sdk#297]
- I am getting 'Instance of 'FetchGistProofException''.
- Already have my own infura api key.
- My .env
<img width="561" alt="Screenshot 2023-05-09 at 13 36 27" src="https://user-images.githubusercontent.com/34487217/237014720-befdc278-5c0d-4006-89b4-49b5945e2b60.png">

![IMG_2585](https://user-images.githubusercontent.com/34487217/237014984-382a5e87-d0c2-454c-b358-7e9262230c88.PNG)
<img width="1258" alt="Screenshot 2023-05-09 at 13 57 49" src="https://user-images.githubusercontent.com/34487217/237020352-22e82cdc-b73c-46bd-803d-88ffccf66f5b.png">

**Comment by plusema86** [comment]
@tranngocthuan1996 thanks for the report, which branch are you using?
