### ISSUE TITLE
Polygon app gives a `credential not found` message for KYCAgeCredential(no req) - sig

### ISSUE THREAD

**Issue by bibash28** [0xPolygonID/polygonid-flutter-sdk#314]
issuer URL:  https://issuer-demo.polygonid.me/
verifier URL: https://verifier-demo.polygonid.me/
Device: iOS(16.4.1)
Tested in: PolygonID App(v2.1.2-2305280)

Step 1: 
`Added Age Credential`

Step 2:
`Used (KYCAgeCredential(no req) - sig)` 

Issue:
How to restrict generating proof? The PolygonID app gives a `credential not found` message. 
![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/18188709/3f1005e7-ef82-478e-bf09-5412abe160dc)

**Comment by rauljareno** [comment]
Using method from`iden3comm.dart` `getClaimsFromIden3Message`, if the list of claimEntity is empty, there is no credential stored in the sdk that fulfills the proof request requirements

**Comment by bibash28** [comment]
In above scenario, I am getting 1 claim. So that I am unable to show 'Credential not found'... @rauljareno

**Comment by bibash28** [comment]
`flutter: [[ClaimEntity] {id: https://self-hosted-platform.polygonid.me/v1/did:polygonid:polygon:mumbai:2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV/claims/1c5d00f0-f95b-11ed-914a-0242ac120005, issuer: did:polygonid:polygon:mumbai:2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV, did: did:polygonid:polygon:mumbai:2qJC2c1Xz2HW5oirkjKaa9CryqHnSNFnZCepAsf4pA, state: ClaimState.active, expiration: 2030-01-01T00:00:00Z, schema: {$schema: http://json-schema.org/draft-07/schema#, type: object, $metadata: {uris: {jsonLdContext: https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld, jsonSchema: https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCAgeCredential-v3.json}}, required: [@context, id, type, issuanceDate, credentialSubject, credentialSchema, credentialStatus, issuer], properties: {@context: {type: [string, array, object]}, id: {type: string}, type: {type: [string, array], items: {type: string}}, issuer: {type: [string, object], format: uri, required: [id], properties: {id: {type: string, format: uri}}}, issuanceDate: {type: string, format: date-time}, expirationDate: {type: string, format: date-time}, credentialSchema: {type: object, required: [id, type], properties: {id: {type: string, format: uri}, type: {type: string}}}, subjectPosition: {type: string, enum: [none, index, value]}, merklizationRootPosition: {type: string, enum: [none, index, value]}, revNonce: {type: integer}, version: {type: integer}, updatable: {type: boolean}, credentialSubject: {type: object, required: [id, birthday, documentType], properties: {id: {title: Credential Subject ID, type: string, format: uri}, birthday: {type: integer}, documentType: {type: integer}}}}}, type: KYCAgeCredential, info: {id: https://self-hosted-platform.polygonid.me/v1/did:polygonid:polygon:mumbai:2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV/claims/1c5d00f0-f95b-11ed-914a-0242ac120005, @context: [https://www.w3.org/2018/credentials/v1, https://schema.iden3.io/core/jsonld/iden3proofs.jsonld, https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld], type: [VerifiableCredential, KYCAgeCredential], expirationDate: 2030-01-01T00:00:00Z, issuanceDate: 2023-05-23T11:15:23.155098384Z, credentialSubject: {id: did:polygonid:polygon:mumbai:2qJC2c1Xz2HW5oirkjKaa9CryqHnSNFnZCepAsf4pA, type: KYCAgeCredential, birthday: 19960424, documentType: 977245}, credentialStatus: {id: https://self-hosted-platform.polygonid.me/v1/did%3Apolygonid%3Apolygon%3Amumbai%3A2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV/claims/revocation/status/3437767343, revocationNonce: 3437767343, type: SparseMerkleTreeProof}, issuer: did:polygonid:polygon:mumbai:2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV, credentialSchema: {id: https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCAgeCredential-v3.json, type: JsonSchemaValidator2018}, proof: [{type: BJJSignature2021, issuerData: {id: did:polygonid:polygon:mumbai:2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV, state: {claimsTreeRoot: f0fb8228fd84182feb7221421f7e561b4cdbfcccc280400c481108546cea892b, value: ae6ea8fb50b545e58efae2bc79ceb0481fc387ad2c7bdf0f37409ee305f99d1e}, authCoreClaim: cca3371a6cb1b715004407e325bd993c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005c4b1b9c3679872cba754fbb1cc8865687f1ffb50169944e6b11f58605d8b40a53fb963c2f4b856c249b2e6e4f9651a579509a97b1e410854cd3114718ffae0a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, mtp: {existence: true, siblings: []}, credentialStatus: {id: https://self-hosted-platform.polygonid.me/v1/did%3Apolygonid%3Apolygon%3Amumbai%3A2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV/claims/revocation/status/0, revocationNonce: 0, type: SparseMerkleTreeProof, statusIssuer: null}}, coreClaim: c9b2370371b7fa8b3dab2a5ba81b68382a00000000000000000000000000000002127e12f992f032743a006023114e8c727b3896fb810c5534e00ed6100d0b00664312e84f4d076819a0ca8a0a0772c53c4c2e5c100a8cecdf97ebca4d10e0020000000000000000000000000000000000000000000000000000000000000000af2ae8cc0000000080d8db700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, signature: 48500136c402b6881b5cfb7dfc361115a41a283ba5c6f36722e1939691acb20be1163e004dcb8eff88f9119587627a2a0896374f727793aa313dd809bb3aa404}]}}]`

**Comment by rauljareno** [comment]
remove the claim from the sdk using `removeClaims` from `credential.dart` passing the claimId @bibash28

**Comment by bibash28** [comment]
I am not getting your point. Why should I remove the claim? @rauljareno

**Comment by bibash28** [comment]
Step 1:
`Added Age Credential`

Step 2:
`Used (KYCAgeCredential(no req) - sig)`

In polygon id app, I am getting 'Credential not found'.

Is this correct behaviour?
@rauljareno

**Comment by rauljareno** [comment]
The full flow have different parts involved, issuer/verifier and wallet, that's why we need all the possible info to provide support, please fill in this form with the right information https://docs.google.com/forms/d/12pdFvzldCNr-jD3jmes5t9A2iRb1MVMxxl069MmH6_4/edit#responses

**Comment by bibash28** [comment]
Issuer URL: https://issuer-demo.polygonid.me/
verifier URL: https://verifier-demo.polygonid.me/
Device: iOS(16.4.1)
Tested in: PolygonID App(v2.1.2-2305280)

Step 1:
`Added Age Credential`

Step 2:
`Used (KYCAgeCredential(no req) - sig)`

In polygon id app, I am getting 'Credential not found'.

**Comment by rauljareno** [comment]
1. What schema url link are you using?
e.g: https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json/KYCEmployee-v101.json

2. What credential type and values are you using?
e.g: "KYCEmployee"

3. If the issue has to do with some proof request or authentication request, Introduce the auth/proof request in json format
e.g: {"id":"62c74742-57b7-4b0e-9245-f97e67d2c16e","typ":"application/iden3comm-plain-json","type":"https://iden3-communication.io/authorization/1.0/request","thid":"62c74742-57b7-4b0e-9245-f97e67d2c16e","body":{"callbackUrl":"https://verifier-v2.polygonid.me/api/callback?sessionId=331349","reason":"test flow","scope":[{"id":1,"circuitId":"credentialAtomicQueryMTPV2","query":{"allowedIssuers":["*"],"context":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v4.jsonld","credentialSubject":{"birthday":{"$lt":20000101}},"type":"KYCAgeCredential"}}]},"from":"did:polygonid:polygon:mumbai:2qLPqvayNQz9TA2r5VPxUugoF18teGU583zJ859wfy"}

**Comment by bibash28** [comment]
I have just submitted

**Comment by bibash28** [comment]
KYCAgeCredential

**Comment by bibash28** [comment]
`{"id":"c5056fd1-375b-41c5-8f01-cd90d5a6c019","typ":"application/iden3comm-plain-json","type":"https://iden3-communication.io/authorization/1.0/request","thid":"c5056fd1-375b-41c5-8f01-cd90d5a6c019","body":{"callbackUrl":"https://self-hosted-demo-backend-platform.polygonid.me/api/callback?sessionId=888869","reason":"test flow","scope":[{"id":1,"circuitId":"credentialAtomicQuerySigV2","query":{"allowedIssuers":["*"],"context":"https://raw.githubusercontent.com/iden3/claim-schema-vocab/main/schemas/json-ld/kyc-v3.json-ld","type":"KYCAgeCredential"}}]},"from":"did:polygonid:polygon:mumbai:2qLhNLVmoQS7pQtpMeKHDqkTcENBZUj1nkZiRNPGgV"}`

**Comment by rauljareno** [comment]
thanks @bibash28 found the issue, will push an update with the fix.

**Comment by bibash28** [comment]
So if the response is `[null]`, you guys are showing `'Credential not found'`. Am I right? @rauljareno

**Comment by rauljareno** [comment]
exactly, that means that the iden3 message contained one query request and that after searching for it, there was no credential found that fulfill the request

**Comment by bibash28** [comment]
Can the response be sth like `[null, null] , [null, claim]` and so on? @rauljareno

**Comment by rauljareno** [comment]
yes, in that case, there are two queries in the proof request, and there are no credentials found in the first option, and there is no credential found for the first query and another one found for the second query in the second option

**Comment by bibash28** [comment]
So in `[null, claim]` case, should we show `'credential not found'` or `allow to generate proof`? @rauljareno

**Comment by rauljareno** [comment]
it depends on the case, you can receive 2 queries in the same proof request , first one optional (age < 18 for example) and second one mandatory (country == Singapore), so in that case you should allow to generate and share the proof for the second query. In case both queries are mandatory, then you should not allow to continue generating the proofs and sharing them

**Comment by bibash28** [comment]
ok.. thanks...

**Comment by rauljareno** [comment]
the number of elements in both lists should be the same, yes

**Comment by bibash28** [comment]
yes.. thanks..
