### ISSUE TITLE
SignOnChain Age (less then 2002/01/01) - sig   opens list of wallets to generate prrof

### ISSUE THREAD

**Issue by bibash28** [0xPolygonID/polygonid-flutter-sdk#319]
Test device: iOS(16.4.1)

1. How to produce this screen?
2. What is the flow? I chose Metamask it just opened the app and nothing happened.

![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/18188709/b85aca57-70b0-46d1-9d10-7e1643d65afe)

**Comment by sanketsaagar** [comment]
Hi @bibash28 , on-chain verification integration with Wallet connect is only implemented on the polygon id app, this is not in the scope of the SDK.

**Comment by bibash28** [comment]
Can you explain the process? Wallet connect is already implemented in our app.

@sanketsaagar @rauljareno
