### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by refi93** [0xPolygonID/polygonid-flutter-sdk#327]
Currently, this Flutter lib seems to support Android and iOS, are there any plans to add web support?

**Comment by plusema86** [comment]
Hi @refi93 , currently PolygonID Flutter SDK is dedicated only to the mobile, for the web you can use this repo https://github.com/0xPolygonID/js-sdk

**Comment by refi93** [comment]
@plusema86 thanks, I noticed the js repo and I know we can make js bindings on top of it in Flutter, but I was hoping for a library for a flutter web app avoiding the need to make such bindings which would also make it more convenient to implement a custom storage interface for the polygon id credentials which is something we wanted to do (and can do, it's just a bit cumbersome with the js api)

**Comment by plusema86** [comment]
@refi93 you're welcome, but unfortunately the SDK is built with mobile in mind, currently it depends on multiple non-web compatible packages (ffi, path_provider etc.), it would require a research and development phase and consequent adaptation of the current SDK, anyway I will propose to include this support in our roadmap, also, if you need js-sdk support feel free to contact us.
