### ISSUE TITLE
Example app throws "Invalid codec signature" upon identity creation

### ISSUE THREAD

**Issue by robgsupsi** [0xPolygonID/polygonid-flutter-sdk#331]
I've tried to build and run the example application included in the repo. I was able to make it work a couple of months ago, but with the new version from the dev branch I get the following error upon creation of an identity:

`[AddNewIdentityUseCase]` Error: [2] Invalid codec signature`

It seems that it's something that has to do with sambast but I have no idea how to solve it.

**Comment by jccy2106** [comment]
I am experiencing the same issue. Both on android emulator and actual Pixel device.

**Comment by plusema86** [comment]
Unfortunately the encrypt package update created this bug, I have hotfixed it on the develop branch, would you please let me know if it works on your projects? thank you for the report

**Comment by robgsupsi** [comment]
@plusema86 thanks for the fix, I can confirm that now it works again
