### ISSUE TITLE
Unable to run example app on linux ubuntu 22.04

### ISSUE THREAD

**Issue by yash-block8** [0xPolygonID/polygonid-flutter-sdk#341]
Building Linux application...                                           

(example:15817): Gdk-CRITICAL **: 11:21:42.314: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: Error while creating BabyjubjubLib
flutter: Stack trace:
 #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      new BabyjubjubLib (package:polygonid_flutter_sdk/identity/libs/bjj/bjj.dart:20:10)
#2      GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:427:45)
#3      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:172:37)
#4      _GetItImplementation.get (package:get_it/get_it_impl.dart:442:34)
#5      GetItHelper.call (package:injectable/src/get_it_helper.dart:45:13)
#6      GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:489:46)
#7      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:172:37)
#8      _GetItImplementation.get (package:get_it/get_it_impl.dart:442:34)
#9      GetItHelper.call (package:injectable/src/get_it_helper.dart:45:13)
#10     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:880:17)
<asynchronous suspension>
#11     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:919:29)
<asynchronous suspension>
#12     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:968:15)
<asynchronous suspension>
#13     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:1140:15)
<asynchronous suspension>
#14     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:1305:11)
<asynchronous suspension>
#15     PolygonIdSdk.init (package:polygonid_flutter_sdk/sdk/polygon_id_sdk.dart:68:22)
<asynchronous suspension>
#16     registerProviders (package:polygonid_flutter_sdk_example/src/presentation/dependency_injection/dependencies_provider.dart:58:3)
<asynchronous suspension>
#17     init (package:polygonid_flutter_sdk_example/src/presentation/dependency_injection/dependencies_provider.dart:26:3)
<asynchronous suspension>
#18     main (package:polygonid_flutter_sdk_example/main.dart:10:3)
<asynchronous suspension>

flutter: Error while creating LibBabyJubJubDataSource
flutter: Stack trace:
 #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      new BabyjubjubLib (package:polygonid_flutter_sdk/identity/libs/bjj/bjj.dart:20:10)
#2      GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:427:45)
#3      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:172:37)
#4      _GetItImplementation.get (package:get_it/get_it_impl.dart:442:34)
#5      GetItHelper.call (package:injectable/src/get_it_helper.dart:45:13)
#6      GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:489:46)
#7      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:172:37)
#8      _GetItImplementation.get (package:get_it/get_it_impl.dart:442:34)
#9      GetItHelper.call (package:injectable/src/get_it_helper.dart:45:13)
#10     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:880:17)
<asynchronous suspension>
#11     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:919:29)
<asynchronous suspension>
#12     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:968:15)
<asynchronous suspension>
#13     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:1140:15)
<asynchronous suspension>
#14     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:1305:11)
<asynchronous suspension>
#15     PolygonIdSdk.init (package:polygonid_flutter_sdk/sdk/polygon_id_sdk.dart:68:22)
<asynchronous suspension>
#16     registerProviders (package:polygonid_flutter_sdk_example/src/presentation/dependency_injection/dependencies_provider.dart:58:3)
<asynchronous suspension>
#17     init (package:polygonid_flutter_sdk_example/src/presentation/dependency_injection/dependencies_provider.dart:26:3)
<asynchronous suspension>
#18     main (package:polygonid_flutter_sdk_example/main.dart:10:3)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'pack_signature': /home/<PATH/>/polygonid-flutter-sdk/example/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so: undefined symbol: pack_signature
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      new BabyjubjubLib (package:polygonid_flutter_sdk/identity/libs/bjj/bjj.dart:20:10)
#2      GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:427:45)
#3      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:172:37)
#4      _GetItImplementation.get (package:get_it/get_it_impl.dart:442:34)
#5      GetItHelper.call (package:injectable/src/get_it_helper.dart:45:13)
#6      GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:489:46)
#7      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:172:37)
#8      _GetItImplementation.get (package:get_it/get_it_impl.dart:442:34)
#9      GetItHelper.call (package:injectable/src/get_it_helper.dart:45:13)
#10     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:880:17)
<asynchronous suspension>
#11     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:919:29)
<asynchronous suspension>
#12     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:968:15)
<asynchronous suspension>
#13     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:1140:15)
<asynchronous suspension>
#14     GetItInjectableX.$initSDKGetIt.<anonymous closure> (package:polygonid_flutter_sdk/sdk/di/injector.config.dart:1305:11)
<asynchronous suspension>
#15     PolygonIdSdk.init (package:polygonid_flutter_sdk/sdk/polygon_id_sdk.dart:68:22)
<asynchronous suspension>
#16     registerProviders (package:polygonid_flutter_sdk_example/src/presentation/dependency_injection/dependencies_provider.dart:58:3)
<asynchronous suspension>
#17     init (package:polygonid_flutter_sdk_example/src/presentation/dependency_injection/dependencies_provider.dart:26:3)
<asynchronous suspension>
#18     main (package:polygonid_flutter_sdk_example/main.dart:10:3)
<asynchronous suspension>

Syncing files to device Linux...                                   778ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Linux is available at: http://127.0.0.1:43829/hxcXbPedQW8=/
The Flutter DevTools debugger and profiler on Linux is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:43829/hxcXbPedQW8=/

**Comment by Groovytent** [comment]
the Flutter SDK runs only on mobile, theoretically a Flutter application can run on Linux, but our SDK uses core libraries built only for iOS and Android

**Comment by yash-block8** [comment]
thanks for the clarifications, closing
