### ISSUE TITLE
Crash when generating authentication token with custom credentials

### ISSUE THREAD

**Issue by otto-mora** [0xPolygonID/polygonid-flutter-sdk#348]
Error reported by user Joan_X1ao in the Polygon ID Discord:

Schema used: https://raw.githubusercontent.com/Xiaod0ng/Schema/main/json-ld/test-Age.json-ld

Steps:
- issuer credential using issuer-ui like normal
- try to verify the credential with specific query type (see notes below)

After some debugging we are able to determine that the this happens with a specific type of query (the greater than query works fine):

![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/16960403/8eb99a89-5d30-40c9-b684-0dffc29eb196)

![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/16960403/fae81c6a-a32a-46ad-9306-a7b91c5c0eb8)

![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/16960403/dba9a243-6937-45ac-b1d8-446178f3a54e)

![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/16960403/9c900482-115f-4748-9d8f-6261a1b37438)

However as explained by the user with the "birthday less than query it fails":

> So I just tried again. Everything's okay when sanning the verifier's QR code. When polygon ID was calculating the proof, at the step of preparing authentication token, it will crash. I have tried verifier-v2 and verifier-demo. I also tried condition like greater than 1, it can generate the proof. So I'm wondering is it because the calculation takes too much time or resource? 

![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/16960403/ed47c455-a476-4473-a587-e787c2d6c067)
![image](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/16960403/4431bbf6-8f85-4b4f-8382-7462cdd1f686)

**Comment by Xiaod0ng** [comment]
Hi Dev team, to add more info to this issue. When the condition is set to EQ, it crashes as well. I'm using Redmi K50 from Xiaomi, android 13. Please tag me if you need other information. Thanks.

**Comment by plusema86** [comment]
hi @Xiaod0ng , just tested with iOS and GT, LT and EQ are working, I'm going to test android

**Comment by plusema86** [comment]
@Xiaod0ng , it is working as expected also for android (Pixel 6) 
@olomix is it possible that we don't support this https://en.wikipedia.org/wiki/Redmi_K50

**Comment by Xiaod0ng** [comment]
@plusema86 Thank you. I will test with other models again. Is there any troubleshooting method to see the logs or errors? I'm not familiar with App development.

**Comment by plusema86** [comment]
you can follow two approaches, first one is from inside the app, in the settings you can enable stacktrace, if errors occur you can read some logs, but from a dev point of view I would always suggest to run example app, you can get it from this repo, run it and monitoring the logs directly from your IDE

**Comment by Xiaod0ng** [comment]
Hi @plusema86, when I tried to verify the credential from the same schema, polygon ID app shows thhe following error.
![new ducument](https://github.com/0xPolygonID/polygonid-flutter-sdk/assets/46312135/91fcf96a-0ed7-44aa-a027-7a53bfbd8e76)
It happens on different models.

**Comment by plusema86** [comment]
@Xiaod0ng are you using schema url or jsonLD? it seems that you're creating a proof request using the wrong one, you need to use jsonLD when creating proof request

**Comment by Xiaod0ng** [comment]
@plusema86 Sorry for late reply. Yes, you are right. I believe I misused the URL when verifying, but the crashing issue still exists. When verifying a credential for the first time, it is very likely that the app will crash.

**Comment by otto-mora** [comment]
@Xiaod0ng Hello Sir. Is this still happening or can we close the issue?

**Comment by Xiaod0ng** [comment]
@otto-mora Hi Otto, it doesn't happen again. With same schema and same model, it doesn't crash no matter using EQ or LT. You may close this issue. BTW, it's she/her.

**Comment by otto-mora** [comment]
Thanks for confirming back. Apologies for my confusion on your name. I will go ahead and close the issue. 👍
